### ISSUE TITLE
Homepage template

### ISSUE THREAD

**Issue by danielpopdan** [drupaltransylvania/drupal-camp#12]
As a product owner
I want the PSD converted to HTML
So that it can be integrated into the website.

**Acceptance criteria**
1. The HTML has to match 100% with the design.
2. The HTML has to be responsive.

Design: https://goo.gl/1YocHs

![homepage](https://user-images.githubusercontent.com/9623300/31127322-3e9082ac-a857-11e7-9095-b7829f8a4bee.jpg)

**Comment by AlexandruSateanuHoria** [comment]
Update: re-arrange elements and height of images after design changes.

The reason for the design change was to have more content in the viewport on page load.
