### ISSUE TITLE
Location page template

### ISSUE THREAD

**Issue by danielpopdan** [drupaltransylvania/drupal-camp#13]
As a product owner 
I want the location PSD converted to HTML 
So that it can be integrated into the website.

**Acceptance criteria**

1. The HTML should reproduce 100% the design
2. The HTML should be responsive/adaptive

Design: https://goo.gl/y6asYG

![location](https://user-images.githubusercontent.com/9623300/31127250-067a819c-a857-11e7-9524-4d0776e47668.jpg)

**Comment by danielpopdan** [comment]
1/ The icon above the title "The office" is missing. 
2/ Cluj-Napoca bellow the title "The office" is missing.
3/ On the slider, the right arrow is overlapping with the last element of the slider.
4/ If you click on an image of the slider, it should zoom out in a popup.

**Comment by AlexandruSateanuHoria** [comment]
First three feedbacks are now fixed.
