### ISSUE TITLE
Sponsors page feedback

### ISSUE THREAD

**Issue by danielpopdan** [drupaltransylvania/drupal-camp#148]
1. On the sponsors page, for "Diamond" sponsors there are a lot of benefits and there should be some empty space between extras and benefits. On mobile, they are overlapping.
2. Please check the media partnership and the form, we can't render them in a container because this are added as separate paragraphs. 
3. Please change the colors for sponsorship boxes:

- Diamond #9CD1D3 
- Gold: The one that is set for Diamond right now.
- Silver: the one that is set for community 
- Community: the one that is set for gold right now.

**Comment by AlexandruSateanuHoria** [comment]
All fixed.
