### ISSUE TITLE
Sponsor contact form template

### ISSUE THREAD

**Issue by danielpopdan** [drupaltransylvania/drupal-camp#17]
As a product owner
I want the PSD converted to HTML based on Drupal output
So that it can be integrated into the website.

**Acceptance criteria**
1. The HTML has to match 100% with the design.
2. The HTML has to be responsive.
3. The output should be similar with Drupal one so it can be integrated easily.

Design: https://goo.gl/o493wA

![sponsors](https://user-images.githubusercontent.com/9623300/31126978-2080bd78-a856-11e7-9730-37e672fd7d13.jpg)

**Comment by corneaalina** [comment]
Sponsors contact form: https://pastebin.com/LkVDdAZH

**Comment by danielpopdan** [comment]
1/ Required stars are missing from the form.
