### ISSUE TITLE
Integrate featured speakers block on homepage

### ISSUE THREAD

**Issue by danielpopdan** [drupaltransylvania/drupal-camp#264]

**Comment by danielpopdan** [comment]
1. Please check the filter structure if you can adapt it to the output. 
2. The "All" option should be hidden from the filters.
3. The images should be rounded. 
4. Make the speakers list centralized, so if there are fewer than 4 speakers they appear on center.

**Comment by OvidiuBojor** [comment]
Task done in #270.
