### ISSUE TITLE
Commerce Tickets

### ISSUE THREAD

**Issue by novaFTL** [drupaltransylvania/drupal-camp#341]
Workflow integration according to specification.

See: https://docs.google.com/document/d/1VhmLXuuT57RDLDs5Vsqkbsy-6y1yJgNF7NVBE215sS8/edit#heading=h.cuul5gu053ns

```
* un user cumpara un numar de bilete
* pentru fiecare bilet cumparat se genereaza un cod unic (tichet)
* tichetele sunt generate si trimise dupa confirmarea platii
* userul o sa aiba toate tichetele pe o pagina din account + email
* optional, se pot asigna emailuri la tichete, fiecare mail o sa primeasca un tichet
* by default, toate tichetele generate nu sunt activate
* un tichet trebuie activat de un user (redeem coupon form?)
* un tichet poate fi activat de un singur user
* un user poate activa un singur tichet (?)

cred ca o sa fie nevoie de o singura entitate

Ticket:
* id
* code (generated)
* buyer (uid)
* activator (null/uid)

Cand se cumpara bilete, se genereaza n entitati ticket, cu code generat, buyer userul care le-a cumparat, activator null

Cand un user incearca sa activeze un bilet, se verifica daca un ticket cu codul pe care userul incearca sa-l activeze exista si nu este activat, si daca un user a activat deja un bilet. Se poate sa nici nu dam acces unui user la formul de activare daca are deja bilet activ.
```

**Comment by novaFTL** [comment]
s-a facut:
* configurare
* colectare mailuri individuale
* generare de coduri
* activare de tichet pe baza de cod
* lista de tichete

mai trebuie facut: 
* trimitere de mailuri pentru coduri
* form pentru persoana/companie
* login redirect

https://github.com/drupaltransylvania/drupal-camp/tree/DCT-341

**Comment by alex-stanciu** [comment]
https://github.com/drupaltransylvania/drupal-camp/pull/421
s-a facut:
    trimitere de mailuri pentru coduri
    form pentru persoana/companie
    login redirect
mai trebuie facut:
    testare flow commerce
    theming flow commerce si mail-uri trimise
